steps:
  - name: ":vitest: Test"
    command: npx vitest --run
    plugins:
      - docker-compose#v4.16.0:
          run: app
  - name: ":prettier: Prettier"
    command: npx prettier . --check
    plugins:
      - docker-compose#v4.16.0:
          run: app
